# appName: test-argo-app
# namespace: default
# replicaCount: 2
# baseDomain: "devopsjourney.com"
# routes:
#   subDomain: "api"
# image:
#   repository: devopsjourney1/mywebapp
#   tag: latest
#   pullPolicy: IfNotPresent
# container:
#   port: 3000
#   env:
#     BG_COLOR: "#FFFFFF"
#     FONT_COLOR: "#000000"
#     CUSTOM_HEADER: "Hello from Helm!"
#   resources:
#     requests:
#       memory: "2Gi"
#       cpu: "2000m"
#     limits:
#       memory: "2Gi"
#       cpu: "2000m"
# service:
#   port: 80
# autoscaling:
#   enabled: true
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 50
#   targetMemoryUtilizationPercentage: 10
# probes:
#   readiness:
#     path: /healthz
#     initialDelaySeconds: 10
#     periodSeconds: 5
#   liveness:
#     path: /healthz
#     initialDelaySeconds: 15
#     periodSeconds: 10
