apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.appName }}-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "{{ .Values.baseDomain }}"
    - "{{ .Values.subDomain }}.{{ .Values.baseDomain }}"
    tls:
      httpsRedirect: false 
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "{{ .Values.baseDomain }}"
    - "{{ .Values.subDomain }}.{{ .Values.baseDomain }}"
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.appName }}-tls
     