{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ default 1 .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
{{- end }}
