apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-active
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - name: http-web
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.appName }}
