apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - name: http-web
    port: {{ .Values.service.port }} 
    protocol: TCP
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP 