{{- if .Values.container.stringMounts }}
{{- range .Values.container.stringMounts }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.appName }}-{{ .name | lower }}
  namespace: {{ $.Values.namespace }}
data:
  {{- range $key, $value := .data }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
