apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "{{ .Values.baseDomain }}"
  - "{{ .Values.routes.subDomain }}.{{ .Values.baseDomain }}"
  gateways:
  - {{ .Values.appName }}-gateway
  http:
  - match:
    - authority:
        exact: "{{ .Values.routes.subDomain }}.{{ .Values.baseDomain }}"
    route:
    - destination:
        host: {{ .Values.appName }}-active
        port:
          number: {{ .Values.service.port }}
  - route:
    - destination:
        host: {{ .Values.appName }}-active
        port:
          number: {{ .Values.service.port }}