apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  {{- range .Values.routes }}
    - "{{ .domain }}"
  {{- end }}
  gateways:
    - istio-system/default-gateway
  http:
  {{- $appName := .Values.appName }}
  {{- $namespace := .Values.namespace }}
  {{- $servicePort := .Values.service.port }}
  {{- range .Values.routes }}
    - match:
        - authority:
            exact: "{{ .domain }}"
      route:
        - destination:
            host: {{ $appName }}-active.{{ $namespace }}.svc.cluster.local
            port:
              number: {{ $servicePort }}
  {{- end }}
