apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "{{ .Values.baseDomain }}"
  - "*.{{ .Values.baseDomain }}"
  - "{{ .Values.routes.subDomain }}.{{ .Values.baseDomain }}"
  gateways:
  - istio-system/default-gateway
  http:
  # - match:
  #   - uri:
  #       prefix: "/.well-known/acme-challenge/"
  #   route:
  #   - destination:
  #       host: cm-acme-http-solver-service
  #       port:
  #         number: 8089
  - match:
    - authority:
        exact: "{{ .Values.routes.subDomain }}.{{ .Values.baseDomain }}"
    route:
    - destination:
        host: {{ .Values.appName }}-active
        port:
          number: {{ .Values.service.port }}
  - route:
    - destination:
        host: {{ .Values.appName }}-active
        port:
          number: {{ .Values.service.port }}

# apiVersion: networking.istio.io/v1beta1
#    kind: VirtualService
#    metadata:
#      name: test-sm-api-19-vs
#      namespace: argocd
#    spec:
#      gateways:
#      - test-sm-api-19-gateway
#      hosts:
#      - "supamail.io"
#      - "*.supamail.io"
#      http:
#      - match:
#        - uri:
#            prefix: "/.well-known/acme-challenge/"
#        route:
#        - destination:
#            host: cm-acme-http-solver-service
#            port:
#              number: 8089
#      - match:
#        - authority:
#            exact: api.supamail.io
#        route:
#        - destination:
#            host: test-sm-api-19-active
#            port:
#              number: 4040
#      - route:
#        - destination:
#            host: test-sm-api-19-active
#            port:
#              number: 4040