apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  {{- range .Values.routes }}
  - "{{ .domain }}"
  {{- end }}
  gateways:
  - istio-system/default-gateway
  http:
  {{- range .Values.routes }}
  - match:
    - authority:
        exact: "{{ .domain }}"
  {{- end }}
    route:
    - destination:
        host: {{ .Values.appName }}-active.{{ .Values.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
  - route:
    - destination:
        host: {{ .Values.appName }}-active.{{ .Values.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
