apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  # - "{{ .Values.baseDomain }}"
  - "{{ .Values.routes.subDomain }}.{{ .Values.baseDomain }}"
  gateways:
  - istio-system/default-gateway
  http:
  # - match:
  #   - uri:
  #       prefix: "/.well-known/acme-challenge/"
  #   route:
  #   - destination:
  #       host: cm-acme-http-solver-service.{{ .Values.namespace }}.svc.cluster.local
  #       port:
  #         number: 8089
  - match:
    - authority:
        exact: "{{ .Values.routes.subDomain }}.{{ .Values.baseDomain }}"
    route:
    - destination:
        host: {{ .Values.appName }}-active.{{ .Values.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
  - route:
    - destination:
        host: {{ .Values.appName }}-active.{{ .Values.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
